CREATE TABLE betreuer_profile
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    github_id VARCHAR,
    name      VARCHAR,
    email     VARCHAR,
    tags      TEXT[],
    CONSTRAINT "pk_betreuer_profıle" PRIMARY KEY (id)
);