CREATE TABLE thema_dto
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titel           VARCHAR,
    beschreibung    VARCHAR,
    voraussetzungen TEXT[],
    CONSTRAINT pk_thema_dto PRIMARY KEY (id)
);